default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || 10 %>
  username: <%= ENV["DB_USERNAME"] || "postgres"  %>
  password: <%= ENV["DB_PASSWORD"] || nil %> 
  host: <%= ENV["DB_HOST"] || "postgres" %>

development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
  database: ar_dev

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  host: localhost
  database: ar_test

production:
  <<: *default
  database: ar
